### PR TITLE
Added transferWithLock function, Badges and restructured code

### PR DESCRIPTION
**Pull request by maxsam4**
- Added transferWithLock function which can be used to transfer tokens into locked balance of a user.
- Modified Travis config to send coverage to coverall and edited readme to show the badges.
- Restructured the code to follow the ERC standard and updated standardToken for proper encapsulation.

### CODE REVIEW

**Review by nitika-goel — COMMENTED** [review]
Thanks for the changes. Just 1 thing here. Why have you added the openzeppelin contracts separately?

**Comment by maxsam4** [comment]
guys over at open-zeppelin haven't updated their npm module yet. They have updated the GitHub repo with latest standard which is incompatible with their npm module, hence, forcing us to either stick with the deprecated standard or import their contracts separately.

**Comment by nitika-goel** [comment]
We're building on top of ERC20. We should use npm modules only and inherit ERC20 instead of Standard token. I just noticed the new Standard Token has mint and burn functions in it. It is more than ERC20. Let's not use it.

**Comment by maxsam4** [comment]
You are confusing implementation with the ERC/EIP. Look at the ERC1132.sol that I have proposed as the ERC1132 interface. It is in line with ERC20. infact, It can be used as an extension to any token, not only ERC20. It can also be used by proxy locking tokens.

LockableToken.sol is a a standard example, a standard implementation of ERC1132. I strongly believe that we should use StandardToken as the base to showcase the standard implementation.

using ERC20 and defining custom transfer and other functions will defeat the whole purpose of this and last PR.

**Comment by nitika-goel** [comment]
ERC1132.sol is great! If you notice, the functions of mintable token and burnable token are now included in Standard Token. Changes are made around 5 days ago and I'm not convinced we should change based on this. It's better if we stick to the older npm version and update once the new version is accepted as a standard.

**Comment by maxsam4** [comment]
They included _mint and _burn to follow the encapsulation principles. We don't really need those functions in lockable token except for the initial minting. I have updated the code to use the npm module. We'll have to update the constructor to use _mint rather than directly modifying balances and total supply once the npm module gets updated (probably in September).

**Comment by maxsam4** [comment]
Coverage is now 100%

**Comment by maxsam4** [comment]
New locking and all unlocking should be cheaper now.

**Comment by maxsam4** [comment]
Gas comparison. Maybe we can add a "default" reason to avoid the cost of pushing a reason.

| Action | Old  | New |
| ------------- | ------------- | ------------- |
| First ever lock of a user  | 137516  | 133881  |
| Locking for a new reason  | 107260  | 103753  |
| Locking for an old reason  | 51623  | ALL LOCKS ARE NEW REASON |
| unlocking 2 reasons  | 71618  | 48723 |
| unlocking 3 reasons  | 97697  | 64943 |

Gas usage for extend lock and lock more tokens is similar. 
The difference in unlocking cost increases with lock reasons as we don't delete the lock reasons in the earlier version so it has to parse through all the irrelevant lock reasons as well.
That being said, this change might not be worth it if we expect people to lock and unlock for the same reason again and again.

**Comment by maxsam4** [comment]
The gas savings are a WIP and I'll create a different PR for them when it's ready.

**Review by davesag — APPROVED** [review]

**Pull request merged**
