### PR TITLE
Syntax error in line 1

### PR DESCRIPTION
**Pull request by acrdlph**

### CODE REVIEW

**Comment by maxsam4** [comment]
Hey @acrdlph, Thanks for taking interest.

I would like to point out that `pragma solidity 0.4.24;` is perfectly fine syntax and intentionally used over `pragma solidity ^0.4.24;`.

The original line means that the contract should be compiled with 0.4.24 version of solidity compiler explicitly while the latter means that the contract can be compiled with any version of solidity compiler newer than 0.4.24.

I prefer keeping solidity version fixed to avoid surprises. There can be breaking changes in the solidity version updates which can cause unintended behavior.

**Review by maxsam4 — CHANGES_REQUESTED** [review]
`pragma solidity 0.4.24;` is a perfectly fine syntax.
It can be changed to `pragma solidity 0.4.25;` though to use the latest stable solidity compiler which is default version on Remix. There is no breaking change introduced in 0.4.25 that concerns this contract.

**Comment by acrdlph** [comment]
woops, ok thanks a lot for the explanation!! still learning ... 
am using these contracts for a [personal attention market](https://github.com/acrdlph/arena) i am building and find them very useful :)

**Comment by nitika-goel** [comment]
Thanks for your interest @acrdlph. I agree with @maxsam4 , let's keep it at a fixed compiler version. Closing the pull request for now.

**Pull request closed without merging**
